version: '3.7'
services:
    adminer:
        image: adminer
        ports:
            - 8080:8080
    db:
        image: mysql
        volumes:
            - ./sql-initialize:/docker-entrypoint-initdb.d
        command: --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
        environment:
            MYSQL_ROOT_PASSWORD: rootadmin
    php:
        build: apache_php_mysqli
        ports:
            - 8888:80
        volumes:
            - ./html_php_files:/var/www/html/
